version: '3'
services:
  node-app:
    image: '239272608624.dkr.ecr.eu-north-1.amazonaws.com/workout-api:IMAGE_TAG'
    links:
      - 'redis'
    ports:
      - 80:80
  redis:
    image: 'redis:alpine3.10'
    volumes:
      - '/var/app/current/redis-volume:/var/lib/redis/data'
